# Generated by Django 5.2.15 on 2026-06-08 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('status', models.CharField(choices=[('assembling', 'Собирается'), ('for_sale', 'На продаже'), ('sold', 'Продан')], default='assembling', max_length=20, verbose_name='Статус')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена продажи')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builds_case', to='inventory.component', verbose_name='Корпус')),
                ('cooler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builds_cooler', to='inventory.component', verbose_name='Охлаждение')),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builds_cpu', to='inventory.component', verbose_name='Процессор')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL)),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builds_gpu', to='inventory.component', verbose_name='Видеокарта')),
                ('motherboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builds_motherboard', to='inventory.component', verbose_name='Материнская плата')),
                ('psu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builds_psu', to='inventory.component', verbose_name='Блок питания')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builds_ram', to='inventory.component', verbose_name='ОЗУ')),
                ('ssd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builds_ssd', to='inventory.component', verbose_name='SSD')),
            ],
            options={
                'verbose_name': 'Сборка ПК',
                'verbose_name_plural': 'Сборки ПК',
                'ordering': ['-created_at'],
            },
        ),
    ]
