# Generated by Django 5.2.15 on 2026-06-08 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
        ('inventory', '0003_assembledpc_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuild',
            name='assembled_pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_builds', to='inventory.assembledpc', verbose_name='Готовый ПК со склада'),
        ),
    ]
