# Generated by Django 5.2.15 on 2026-06-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_actionlog_assembledpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembledpc',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
